name: japan_prefectures_selector
description: A new flutter plugin project.
version: 0.0.1
author: Panu Avakul
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

